window:
  decorations: none
  startup_mode: Maximized

scrolling:
  history: 100000

font:
  normal:
    family: Victor Mono Nerd Font
    style: Regular
  bold:
    family: Victor Mono Nerd Font
    style: Bold
  italic:
    family: Victor Mono Nerd Font
    style: Italic
  bold_italic:
    family: Victor Mono Nerd Font
    style: Bold Italic
  size: 21

