lastupdatecheck: 0
recentrepos:
- /home/daniel/.dotfiles
- /home/daniel/code/portal-website
- /home/daniel/code/cohort-four
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
